#Server configuration
server.port=6664
#server.address=localhost
server.servlet.context-path=/beatms
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
#Server name
spring.application.name=beatms
#Eureka
eureka.client.serviceUrl.defaultZone=${SERVICE_URL_DEFAULT_ZONE}
### DATABASE ###
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bienetreautravail?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
### Email ###
spring.mail.host=smtp-mail.outlook.com
spring.mail.port=587
spring.mail.username=bienetretravail@outlook.com
spring.mail.password=v@Q56yp8IzaT
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
### Paypal ###
paypal.mode=sandbox
paypal.client.id=AUAPugImd4Est0imGmhqSJ92BbkZ0WXfqjf7pRQORtvub3sgfCFVrAFIdBo5PDM_JIYs9UdGrOSXPUct
paypal.client.secret=EJyb6pF_btuLSgCvlOXGXMBhRRxpjx2VUQgMCjFTr0Jbov77ZHHyZGqlsRIEgPAtaa3cmZwsC5A8OVeh
#allowed origins
app.cors.allowedOrigins=http://localhost:4200
#JWT
app.jwtSecret=A9a02115a835ee03d5fb83cd8a468ea33e4090AJ87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675fJ
app.jwtExpirationInMs=604800000
application.security.disabled=true